command:
  - ${env}
  - python
  - -m
  - src.ppo_lstm.main
  - --sweep
  - ${args}
method: bayes
metric:
  name: episode/return_ema
  goal: maximize
parameters:
  wandb_group: 
    values: ['sweeps_3x3_S9_hidden8']  # Now in a list
  hidden_size:
    values: [8]
  learning_rate:
    distribution: log_uniform_values
    min: 5e-5
    max: 3e-3
  hidden_layer_size:
    values: [64, 128, 256]