command:
  - ${env}
  - python
  - -m
  - src.ppo_lstm.main
  - --sweep
  - ${args}
method: bayes
metric:
  name: episode/return_ema
  goal: maximize
parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 1e-3
    max: 2e-3
  num_steps:
    values: [32, 64, 128]
  hidden_size:
    values: [2, 4, 6, 8]
  hidden_layer_size:
    values: [32, 64]
  vf_coef:
    distribution: uniform
    min: 0.5
    max: 1.5 
  seq_len:
    values: [8]